# A Dockstore service entrypoint to a simple jupyter environment..
version: 1.1
service:
  subclass: DOCKER_COMPOSE
  name: Jupyterlab

  authors:
    - name: David Steinberg
  description: Runs a local jupyter service for interactive notebooks at port 8888
  publish: true

  files:
    - docker-compose.yml
    - configure_environment.sh
    - hello.ipynb
  scripts:
    start: docker-compose up
    postprovision:
    port:
    stop: docker-compose down
